name: Elixir CI

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "latest"
          otp-version: "latest"

      - name: Run Elixir script
        run: elixir hello-world.exs
